# Atributos Basicos de un DataFrame

### 1. Lectura de un DataFrame

In [3]:
# Importar la libreria
import pandas as pd
# Usar read_csv para leer el set de datos (dataset) peliculas csv
df = pd.read_csv("../data/peliculas.csv")
# mostrar en pantalla el resultado
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [5]:
df = pd.read_csv("../data/peliculas.csv", usecols=['color', 'director_name', 'num_critic_for_reviews'])
df

      color      director_name  num_critic_for_reviews
0     Color      James Cameron                   723.0
1     Color     Gore Verbinski                   302.0
2     Color         Sam Mendes                   602.0
3     Color  Christopher Nolan                   813.0
4       NaN        Doug Walker                     NaN
...     ...                ...                     ...
4911  Color        Scott Smith                     1.0
4912  Color                NaN                    43.0
4913  Color   Benjamin Roberds                    13.0
4914  Color        Daniel Hsia                    14.0
4915  Color           Jon Gunn                    43.0

[4916 rows x 3 columns]

In [6]:
df = pd.read_csv("../data/peliculas.csv", 
                usecols=['color', 'director_name', 'num_critic_for_reviews'],
                nrows = 100)
df

    color      director_name  num_critic_for_reviews
0   Color      James Cameron                   723.0
1   Color     Gore Verbinski                   302.0
2   Color         Sam Mendes                   602.0
3   Color  Christopher Nolan                   813.0
4     NaN        Doug Walker                     NaN
..    ...                ...                     ...
95  Color         James Gunn                   653.0
96  Color  Christopher Nolan                   712.0
97  Color  Christopher Nolan                   642.0
98  Color       Hideaki Anno                     1.0
99  Color      Peter Jackson                   645.0

[100 rows x 3 columns]

### 2. Principales Atributos de un DataFrame

In [ ]:
# numeros de filas y columnas de un dataframe
df.shape

(100, 3)

In [11]:
print(f"Numero de filas: {df.shape[0]}")  # numero de filas
print(f"Numero de columnas: {df.shape[1]}") # numero de columnas

Numero de filas: 100
Numero de columnas: 3

In [13]:
indice = df.index
print(indice)
print(type(indice))

RangeIndex(start=0, stop=100, step=1)
<class 'pandas.RangeIndex'>

In [14]:
columnas = df.columns
print(columnas)
print(type(columnas))

Index(['color', 'director_name', 'num_critic_for_reviews'], dtype='str')
<class 'pandas.Index'>

In [15]:
datos = df.values
print(datos)
print(type(datos))

[['Color' 'James Cameron' 723.0]
 ['Color' 'Gore Verbinski' 302.0]
 ['Color' 'Sam Mendes' 602.0]
 ['Color' 'Christopher Nolan' 813.0]
 [nan 'Doug Walker' nan]
 ['Color' 'Andrew Stanton' 462.0]
 ['Color' 'Sam Raimi' 392.0]
 ['Color' 'Nathan Greno' 324.0]
 ['Color' 'Joss Whedon' 635.0]
 ['Color' 'David Yates' 375.0]
 ['Color' 'Zack Snyder' 673.0]
 ['Color' 'Bryan Singer' 434.0]
 ['Color' 'Marc Forster' 403.0]
 ['Color' 'Gore Verbinski' 313.0]
 ['Color' 'Gore Verbinski' 450.0]
 ['Color' 'Zack Snyder' 733.0]
 ['Color' 'Andrew Adamson' 258.0]
 ['Color' 'Joss Whedon' 703.0]
 ['Color' 'Rob Marshall' 448.0]
 ['Color' 'Barry Sonnenfeld' 451.0]
 ['Color' 'Peter Jackson' 422.0]
 ['Color' 'Marc Webb' 599.0]
 ['Color' 'Ridley Scott' 343.0]
 ['Color' 'Peter Jackson' 509.0]
 ['Color' 'Chris Weitz' 251.0]
 ['Color' 'Peter Jackson' 446.0]
 ['Color' 'James Cameron' 315.0]
 ['Color' 'Anthony Russo' 516.0]
 ['Color' 'Peter Berg' 377.0]
 ['Color' 'Colin Trevorrow' 644.0]
 ['Color' 'Sam Mendes' 750.0]
 ['Color' 'Sam Raimi' 300.0]
 ['Color' 'Shane Black' 608.0]
 ['Color' 'Tim Burton' 451.0]
 ['Color' 'Brett Ratner' 334.0]
 ['Color' 'Dan Scanlon' 376.0]
 ['Color' 'Michael Bay' 366.0]
 ['Color' 'Michael Bay' 378.0]
 ['Color' 'Sam Raimi' 525.0]
 ['Color' 'Marc Webb' 495.0]
 ['Color' 'Joseph Kosinski' 469.0]
 ['Color' 'John Lasseter' 304.0]
 ['Color' 'Martin Campbell' 436.0]
 ['Color' 'Lee Unkrich' 453.0]
 ['Color' 'McG' 422.0]
 ['Color' 'James Wan' 424.0]
 ['Color' 'Marc Forster' 654.0]
 ['Color' 'Bryan Singer' 539.0]
 ['Color' 'J.J. Abrams' 590.0]
 ['Color' 'Bryan Singer' 338.0]
 ['Color' 'Baz Luhrmann' 490.0]
 ['Color' 'Mike Newell' 306.0]
 ['Color' 'Guillermo del Toro' 575.0]
 ['Color' 'Michael Bay' 428.0]
 ['Color' 'Steven Spielberg' 470.0]
 ['Color' 'Peter Sohn' 298.0]
 ['Color' 'Mark Andrews' 488.0]
 ['Color' 'Justin Lin' 322.0]
 ['Color' 'Andrew Stanton' 421.0]
 ['Color' 'Brett Ratner' 162.0]
 ['Color' 'Roland Emmerich' 367.0]
 ['Color' 'Robert Zemeckis' 240.0]
 ['Color' 'Lana Wachowski' 384.0]
 ['Color' 'David Yates' 248.0]
 ['Color' 'Andrew Adamson' 284.0]
 ['Color' 'Bryan Singer' 396.0]
 ['Color' 'Christopher Nolan' 645.0]
 ['Color' 'Pete Docter' 408.0]
 ['Color' 'Rob Letterman' 219.0]
 ['Color' 'Jon Favreau' 486.0]
 ['Color' 'Martin Scorsese' 682.0]
 ['Color' 'Barry Sonnenfeld' 85.0]
 ['Color' 'Rob Cohen' 264.0]
 ['Color' 'David Ayer' 418.0]
 ['Color' 'Tom Shadyac' 186.0]
 ['Color' 'Doug Liman' 585.0]
 ['Color' 'Kevin Reynolds' 91.0]
 ['Color' 'Stephen Sommers' 250.0]
 ['Color' 'Pete Docter' 536.0]
 ['Color' 'Jon Favreau' 370.0]
 ['Color' 'Jon Favreau' 453.0]
 ['Color' 'Rupert Sanders' 416.0]
 ['Color' 'Robert Stromberg' 401.0]
 ['Color' 'Matt Reeves' 521.0]
 ['Color' 'Roland Joffé' 10.0]
 ['Color' 'Carl Rinsch' 218.0]
 ['Color' 'Anthony Russo' 576.0]
 ['Color' 'Mike Mitchell' 226.0]
 ['Color' 'Brad Bird' 443.0]
 ['Color' 'Don Hall' 384.0]
 ['Color' 'Rich Moore' 377.0]
 ['Color' 'Robert Zemeckis' 188.0]
 ['Color' 'Roland Emmerich' 286.0]
 ['Color' 'Dean DeBlois' 288.0]
 ['Color' 'Jonathan Mostow' 280.0]
 ['Color' 'James Gunn' 653.0]
 ['Color' 'Christopher Nolan' 712.0]
 ['Color' 'Christopher Nolan' 642.0]
 ['Color' 'Hideaki Anno' 1.0]
 ['Color' 'Peter Jackson' 645.0]]
<class 'numpy.ndarray'>

In [17]:
datosnp = df.to_numpy()
print(datosnp)
print(type(datosnp))

[['Color' 'James Cameron' 723.0]
 ['Color' 'Gore Verbinski' 302.0]
 ['Color' 'Sam Mendes' 602.0]
 ['Color' 'Christopher Nolan' 813.0]
 [nan 'Doug Walker' nan]
 ['Color' 'Andrew Stanton' 462.0]
 ['Color' 'Sam Raimi' 392.0]
 ['Color' 'Nathan Greno' 324.0]
 ['Color' 'Joss Whedon' 635.0]
 ['Color' 'David Yates' 375.0]
 ['Color' 'Zack Snyder' 673.0]
 ['Color' 'Bryan Singer' 434.0]
 ['Color' 'Marc Forster' 403.0]
 ['Color' 'Gore Verbinski' 313.0]
 ['Color' 'Gore Verbinski' 450.0]
 ['Color' 'Zack Snyder' 733.0]
 ['Color' 'Andrew Adamson' 258.0]
 ['Color' 'Joss Whedon' 703.0]
 ['Color' 'Rob Marshall' 448.0]
 ['Color' 'Barry Sonnenfeld' 451.0]
 ['Color' 'Peter Jackson' 422.0]
 ['Color' 'Marc Webb' 599.0]
 ['Color' 'Ridley Scott' 343.0]
 ['Color' 'Peter Jackson' 509.0]
 ['Color' 'Chris Weitz' 251.0]
 ['Color' 'Peter Jackson' 446.0]
 ['Color' 'James Cameron' 315.0]
 ['Color' 'Anthony Russo' 516.0]
 ['Color' 'Peter Berg' 377.0]
 ['Color' 'Colin Trevorrow' 644.0]
 ['Color' 'Sam Mendes' 750.0]
 ['Color' 'Sam Raimi' 300.0]
 ['Color' 'Shane Black' 608.0]
 ['Color' 'Tim Burton' 451.0]
 ['Color' 'Brett Ratner' 334.0]
 ['Color' 'Dan Scanlon' 376.0]
 ['Color' 'Michael Bay' 366.0]
 ['Color' 'Michael Bay' 378.0]
 ['Color' 'Sam Raimi' 525.0]
 ['Color' 'Marc Webb' 495.0]
 ['Color' 'Joseph Kosinski' 469.0]
 ['Color' 'John Lasseter' 304.0]
 ['Color' 'Martin Campbell' 436.0]
 ['Color' 'Lee Unkrich' 453.0]
 ['Color' 'McG' 422.0]
 ['Color' 'James Wan' 424.0]
 ['Color' 'Marc Forster' 654.0]
 ['Color' 'Bryan Singer' 539.0]
 ['Color' 'J.J. Abrams' 590.0]
 ['Color' 'Bryan Singer' 338.0]
 ['Color' 'Baz Luhrmann' 490.0]
 ['Color' 'Mike Newell' 306.0]
 ['Color' 'Guillermo del Toro' 575.0]
 ['Color' 'Michael Bay' 428.0]
 ['Color' 'Steven Spielberg' 470.0]
 ['Color' 'Peter Sohn' 298.0]
 ['Color' 'Mark Andrews' 488.0]
 ['Color' 'Justin Lin' 322.0]
 ['Color' 'Andrew Stanton' 421.0]
 ['Color' 'Brett Ratner' 162.0]
 ['Color' 'Roland Emmerich' 367.0]
 ['Color' 'Robert Zemeckis' 240.0]
 ['Color' 'Lana Wachowski' 384.0]
 ['Color' 'David Yates' 248.0]
 ['Color' 'Andrew Adamson' 284.0]
 ['Color' 'Bryan Singer' 396.0]
 ['Color' 'Christopher Nolan' 645.0]
 ['Color' 'Pete Docter' 408.0]
 ['Color' 'Rob Letterman' 219.0]
 ['Color' 'Jon Favreau' 486.0]
 ['Color' 'Martin Scorsese' 682.0]
 ['Color' 'Barry Sonnenfeld' 85.0]
 ['Color' 'Rob Cohen' 264.0]
 ['Color' 'David Ayer' 418.0]
 ['Color' 'Tom Shadyac' 186.0]
 ['Color' 'Doug Liman' 585.0]
 ['Color' 'Kevin Reynolds' 91.0]
 ['Color' 'Stephen Sommers' 250.0]
 ['Color' 'Pete Docter' 536.0]
 ['Color' 'Jon Favreau' 370.0]
 ['Color' 'Jon Favreau' 453.0]
 ['Color' 'Rupert Sanders' 416.0]
 ['Color' 'Robert Stromberg' 401.0]
 ['Color' 'Matt Reeves' 521.0]
 ['Color' 'Roland Joffé' 10.0]
 ['Color' 'Carl Rinsch' 218.0]
 ['Color' 'Anthony Russo' 576.0]
 ['Color' 'Mike Mitchell' 226.0]
 ['Color' 'Brad Bird' 443.0]
 ['Color' 'Don Hall' 384.0]
 ['Color' 'Rich Moore' 377.0]
 ['Color' 'Robert Zemeckis' 188.0]
 ['Color' 'Roland Emmerich' 286.0]
 ['Color' 'Dean DeBlois' 288.0]
 ['Color' 'Jonathan Mostow' 280.0]
 ['Color' 'James Gunn' 653.0]
 ['Color' 'Christopher Nolan' 712.0]
 ['Color' 'Christopher Nolan' 642.0]
 ['Color' 'Hideaki Anno' 1.0]
 ['Color' 'Peter Jackson' 645.0]]
<class 'numpy.ndarray'>

In [19]:
print(df.shape)
print(datos.shape)
print(datosnp.shape)

(100, 3)
(100, 3)
(100, 3)