# Seleccion y manipulacio de columnas y filas

- Diferentes formas de seleccionar una o multiples columnas de nuestro DataFrame
- Diferentes formas de seleccionar una o multiples filas de nuestro DataFrame
- Como seleccionar porciones de nuestro DataFrame (es decir un rango de filas y columnas)
- Como modificar columnas y filas del DataFrame (cambiar nombre, eliminar, agregar...)

In [2]:
import pandas as pd

df = pd.read_csv('../data/peliculas.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

### 1. Seleccion de columnas

In [3]:
# seleccion de una columna

# fb_likes = df['movie_facebook_likes']
fb_likes = df.movie_facebook_likes
fb_likes

0        33000
1            0
2        85000
3       164000
4            0
         ...
4911        84
4912     32000
4913        16
4914       660
4915       456
Name: movie_facebook_likes, Length: 4916, dtype: int64

In [4]:
type(fb_likes)

pandas.Series

In [5]:
# seleccion de muliples columnas

df_cols = df[['director_name', 'duration', 'gross']]
df_cols

          director_name  duration        gross
0         James Cameron     178.0  760505847.0
1        Gore Verbinski     169.0  309404152.0
2            Sam Mendes     148.0  200074175.0
3     Christopher Nolan     164.0  448130642.0
4           Doug Walker       NaN          NaN
...                 ...       ...          ...
4911        Scott Smith      87.0          NaN
4912                NaN      43.0          NaN
4913   Benjamin Roberds      76.0          NaN
4914        Daniel Hsia     100.0      10443.0
4915           Jon Gunn      90.0      85222.0

[4916 rows x 3 columns]

Tambien podemos hacer uso de la propiedad `loc`

In [6]:
df.loc[:,['duration', 'gross']]

      duration        gross
0        178.0  760505847.0
1        169.0  309404152.0
2        148.0  200074175.0
3        164.0  448130642.0
4          NaN          NaN
...        ...          ...
4911      87.0          NaN
4912      43.0          NaN
4913      76.0          NaN
4914     100.0      10443.0
4915      90.0      85222.0

[4916 rows x 2 columns]

El metodo `select_dtype` permite seleccionar columnas con base en el tipo de dato

In [7]:
df.dtypes.value_counts()

float64    13
str        12
int64       3
Name: count, dtype: int64

In [8]:
# seleccionar solo las columas de tipo "int64"

# df_int64 = df.select_dtypes(include='int64')
df_int64 = df.select_dtypes(include=['int64'])
df_int64

      num_voted_users  cast_total_facebook_likes  movie_facebook_likes
0              886204                       4834                 33000
1              471220                      48350                     0
2              275868                      11700                 85000
3             1144337                     106759                164000
4                   8                        143                     0
...               ...                        ...                   ...
4911              629                       2283                    84
4912            73839                       1753                 32000
4913               38                          0                    16
4914             1255                       2386                   660
4915             4285                        163                   456

[4916 rows x 3 columns]

In [9]:
# seleccionar solo las columas de tipo "float64"

df_float64 = df.select_dtypes(include='float64')
df_float64

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35
4,NaN,NaN,131.0,NaN,131.0,NaN,0.0,NaN,NaN,NaN,12.0,7.1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,1.0,87.0,2.0,318.0,637.0,NaN,2.0,6.0,NaN,2013.0,470.0,7.7,NaN
4912,43.0,43.0,NaN,319.0,841.0,NaN,1.0,359.0,NaN,NaN,593.0,7.5,16.00
4913,13.0,76.0,0.0,0.0,0.0,NaN,0.0,3.0,1400.0,2013.0,0.0,6.3,NaN
4914,14.0,100.0,0.0,489.0,946.0,10443.0,5.0,9.0,NaN,2012.0,719.0,6.3,2.35
4915,43.0,90.0,16.0,16.0,86.0,85222.0,0.0,84.0,1100.0,2004.0,23.0,6.6,1.85

In [10]:
# df_num = df.select_dtypes(include='number')
df_num = df.select_dtypes(include=['int64', 'float64'])
df_num

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,723.0,178.0,0.0,855.0,1000.0,760505847.0,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,302.0,169.0,563.0,1000.0,40000.0,309404152.0,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,602.0,148.0,0.0,161.0,11000.0,200074175.0,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,813.0,164.0,22000.0,23000.0,27000.0,448130642.0,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,NaN,131.0,NaN,131.0,NaN,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,1.0,87.0,2.0,318.0,637.0,NaN,629,2283,2.0,6.0,NaN,2013.0,470.0,7.7,NaN,84
4912,43.0,43.0,NaN,319.0,841.0,NaN,73839,1753,1.0,359.0,NaN,NaN,593.0,7.5,16.00,32000
4913,13.0,76.0,0.0,0.0,0.0,NaN,38,0,0.0,3.0,1400.0,2013.0,0.0,6.3,NaN,16
4914,14.0,100.0,0.0,489.0,946.0,10443.0,1255,2386,5.0,9.0,NaN,2012.0,719.0,6.3,2.35,660
4915,43.0,90.0,16.0,16.0,86.0,85222.0,4285,163,0.0,84.0,1100.0,2004.0,23.0,6.6,1.85,456

In [11]:

df_fb = df.filter(like='facebook')
df_fb

,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,cast_total_facebook_likes,actor_2_facebook_likes,movie_facebook_likes
0,0.0,855.0,1000.0,4834,936.0,33000
1,563.0,1000.0,40000.0,48350,5000.0,0
2,0.0,161.0,11000.0,11700,393.0,85000
3,22000.0,23000.0,27000.0,106759,23000.0,164000
4,131.0,NaN,131.0,143,12.0,0
...,...,...,...,...,...,...
4911,2.0,318.0,637.0,2283,470.0,84
4912,NaN,319.0,841.0,1753,593.0,32000
4913,0.0,0.0,0.0,0,0.0,16
4914,0.0,489.0,946.0,2386,719.0,660
4915,16.0,16.0,86.0,163,23.0,456

### 2. Seleccion de filas

En este caso disponemos de los metodos `iloc` (seleccion en base en el indice) y `loc` (usado anteriormente)

In [12]:
# seleccionar una fila con nase en un indice (iloc)
row_3 = df.iloc[3]
row_3

color                                                                    Color
director_name                                                Christopher Nolan
num_critic_for_reviews                                                   813.0
duration                                                                 164.0
director_facebook_likes                                                22000.0
actor_3_facebook_likes                                                 23000.0
actor_2_name                                                    Christian Bale
actor_1_facebook_likes                                                 27000.0
gross                                                              448130642.0
genres                                                         Action|Thriller
actor_1_name                                                         Tom Hardy
movie_title                                              The Dark Knight Rises
num_voted_users                                                        1144337
cast_total_facebook_likes                                               106759
actor_3_name                                              Joseph Gordon-Levitt
facenumber_in_poster                                                       0.0
plot_keywords                deception|imprisonment|lawlessness|police offi...
movie_imdb_link              http://www.imdb.com/title/tt1345836/?ref_=fn_t...
num_user_for_reviews                                                    2701.0
language                                                               English
country                                                                    USA
content_rating                                                           PG-13
budget                                                             250000000.0
title_year                                                              2012.0
actor_2_facebook_likes                                                 23000.0
imdb_score                                                                 8.5
aspect_ratio                                                              2.35
movie_facebook_likes                                                    164000
Name: 3, dtype: object

In [13]:
# seleccion de un afila, pandas retorna una serie
type(row_3)

pandas.Series

In [14]:
# seleccionar filas de la 3 a la 6
row_3_6 = df.iloc[3:7]
row_3_6

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0

In [15]:
# seleccionar solo las filas para las cuales la columna "director_name" es igual a "Steven Spielberg"

df_ss = df.loc[df['director_name']=='Steven Spielberg']
df_ss

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
54,Color,Steven Spielberg,470.0,122.0,14000.0,1000.0,Ray Winstone,11000.0,317011114.0,Action|Adventure|Fantasy,...,2054.0,English,USA,PG-13,185000000.0,2008.0,1000.0,6.2,2.35,5000
177,Color,Steven Spielberg,252.0,117.0,14000.0,358.0,Penelope Wilton,535.0,52792307.0,Adventure|Family|Fantasy,...,106.0,English,UK,PG,140000000.0,2016.0,400.0,6.8,2.35,27000
187,Color,Steven Spielberg,401.0,116.0,14000.0,807.0,Lisa Ann Walter,10000.0,234277056.0,Adventure|Sci-Fi|Thriller,...,2741.0,English,USA,PG-13,132000000.0,2005.0,1000.0,6.5,1.85,0
192,Color,Steven Spielberg,440.0,107.0,14000.0,845.0,Mackenzie Crook,2000.0,77564037.0,Action|Adventure|Family|Mystery,...,447.0,English,USA,PG,135000000.0,2011.0,871.0,7.4,2.35,44000
281,Color,Steven Spielberg,252.0,145.0,14000.0,533.0,Frank Grillo,10000.0,132014112.0,Action|Mystery|Sci-Fi|Thriller,...,1331.0,English,USA,PG-13,102000000.0,2002.0,798.0,7.7,2.35,0
369,Color,Steven Spielberg,281.0,146.0,14000.0,681.0,William Hurt,3000.0,78616689.0,Adventure|Drama|Sci-Fi,...,2153.0,English,USA,PG-13,100000000.0,2001.0,882.0,7.1,1.85,11000
517,Color,Steven Spielberg,177.0,129.0,14000.0,227.0,Richard Schiff,610.0,229074524.0,Action|Adventure|Sci-Fi,...,552.0,English,USA,PG-13,73000000.0,1997.0,506.0,6.5,1.85,0
530,Color,Steven Spielberg,151.0,128.0,14000.0,232.0,Chi McBride,15000.0,77032279.0,Comedy|Drama,...,596.0,English,USA,PG-13,60000000.0,2004.0,466.0,7.3,1.85,16000
539,Color,Steven Spielberg,298.0,163.0,14000.0,412.0,Moritz Bleibtreu,745.0,47379090.0,Drama|History|Thriller,...,824.0,English,France,R,70000000.0,2005.0,486.0,7.6,2.35,0
583,Color,Steven Spielberg,75.0,142.0,14000.0,5000.0,Julia Roberts,49000.0,119654900.0,Adventure|Comedy|Family|Fantasy,...,363.0,English,USA,PG,70000000.0,1991.0,8000.0,6.7,2.35,13000
597,Black and White,Steven Spielberg,388.0,146.0,14000.0,979.0,Benedict Cumberbatch,25000.0,79883359.0,Drama|War,...,488.0,English,USA,PG-13,66000000.0,2011.0,19000.0,7.2,2.35,28000
641,Color,Steven Spielberg,219.0,169.0,14000.0,13000.0,Vin Diesel,15000.0,216119491.0,Action|Drama|War,...,2277.0,English,USA,R,70000000.0,1998.0,14000.0,8.6,1.85,22000
646,Color,Steven Spielberg,538.0,150.0,14000.0,655.0,Hal Holbrook,23000.0,182204440.0,Biography|Drama|History|War,...,720.0,English,USA,PG-13,65000000.0,2012.0,826.0,7.4,2.35,71000
689,Color,Steven Spielberg,308.0,127.0,14000.0,191.0,Ariana Richards,967.0,356784000.0,Adventure|Sci-Fi|Thriller,...,895.0,English,USA,PG-13,63000000.0,1993.0,610.0,8.1,1.85,19000
902,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,667.0,English,USA,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000
1030,Color,Steven Spielberg,149.0,127.0,14000.0,440.0,Julian Glover,11000.0,197171806.0,Action|Adventure|Fantasy,...,477.0,English,USA,PG-13,48000000.0,1989.0,844.0,8.3,2.35,0
1213,Color,Steven Spielberg,459.0,142.0,14000.0,423.0,Mark Rylance,15000.0,72306065.0,Drama|History|Thriller,...,355.0,English,USA,PG-13,40000000.0,2015.0,535.0,7.6,2.35,55000
1237,Color,Steven Spielberg,77.0,155.0,14000.0,11000.0,Morgan Freeman,12000.0,44175394.0,Drama|History,...,227.0,English,USA,R,36000000.0,1997.0,11000.0,7.2,1.85,0
1541,Color,Steven Spielberg,56.0,142.0,14000.0,642.0,John Belushi,16000.0,NaN,Action|Comedy|War,...,217.0,English,USA,PG,35000000.0,1979.0,1000.0,5.9,2.35,2000
1733,Color,Steven Spielberg,148.0,118.0,14000.0,237.0,Amrish Puri,11000.0,179870271.0,Action|Adventure,...,524.0,English,USA,PG,28000000.0,1984.0,429.0,7.6,2.35,0
1857,Black and White,Steven Spielberg,174.0,185.0,14000.0,212.0,Embeth Davidtz,14000.0,96067179.0,Biography|Drama|History,...,1273.0,English,USA,R,22000000.0,1993.0,795.0,8.9,1.85,41000
2128,Color,Steven Spielberg,234.0,115.0,14000.0,488.0,Karen Allen,11000.0,242374454.0,Action|Adventure,...,771.0,English,USA,PG,18000000.0,1981.0,783.0,8.5,2.35,16000
2130,Color,Steven Spielberg,171.0,135.0,14000.0,252.0,Teri Garr,559.0,128300000.0,Drama|Sci-Fi,...,339.0,English,USA,PG,19400870.0,1977.0,481.0,7.7,2.35,0
2575,Color,Steven Spielberg,70.0,154.0,14000.0,271.0,Rae Dawn Chong,852.0,94175854.0,Drama,...,199.0,English,USA,PG-13,15000000.0,1985.0,581.0,7.8,1.85,6000
2870,Color,Steven Spielberg,385.0,130.0,14000.0,366.0,Robert Shaw,813.0,260000000.0,Adventure|Drama|Thriller,...,962.0,English,USA,PG,8000000.0,1975.0,559.0,8.0,2.35,21000
3028,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434949459.0,Family|Sci-Fi,...,515.0,English,USA,PG,10500000.0,1982.0,725.0,7.9,1.85,34000

In [16]:
# seleccionar solo las filas para las cuales la columna "director_name"
# es igual a "Steven Spielberg" o "Quentin Tarantino"
df_ss_qt = df.loc[(df['director_name']=='Steven Spielberg') | (df['director_name']=='Quentin Tarantino')] 
df_ss_qt

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
54,Color,Steven Spielberg,470.0,122.0,14000.0,1000.0,Ray Winstone,11000.0,317011114.0,Action|Adventure|Fantasy,...,2054.0,English,USA,PG-13,185000000.0,2008.0,1000.0,6.2,2.35,5000
177,Color,Steven Spielberg,252.0,117.0,14000.0,358.0,Penelope Wilton,535.0,52792307.0,Adventure|Family|Fantasy,...,106.0,English,UK,PG,140000000.0,2016.0,400.0,6.8,2.35,27000
187,Color,Steven Spielberg,401.0,116.0,14000.0,807.0,Lisa Ann Walter,10000.0,234277056.0,Adventure|Sci-Fi|Thriller,...,2741.0,English,USA,PG-13,132000000.0,2005.0,1000.0,6.5,1.85,0
192,Color,Steven Spielberg,440.0,107.0,14000.0,845.0,Mackenzie Crook,2000.0,77564037.0,Action|Adventure|Family|Mystery,...,447.0,English,USA,PG,135000000.0,2011.0,871.0,7.4,2.35,44000
281,Color,Steven Spielberg,252.0,145.0,14000.0,533.0,Frank Grillo,10000.0,132014112.0,Action|Mystery|Sci-Fi|Thriller,...,1331.0,English,USA,PG-13,102000000.0,2002.0,798.0,7.7,2.35,0
293,Color,Quentin Tarantino,765.0,165.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,2.35,199000
369,Color,Steven Spielberg,281.0,146.0,14000.0,681.0,William Hurt,3000.0,78616689.0,Adventure|Drama|Sci-Fi,...,2153.0,English,USA,PG-13,100000000.0,2001.0,882.0,7.1,1.85,11000
517,Color,Steven Spielberg,177.0,129.0,14000.0,227.0,Richard Schiff,610.0,229074524.0,Action|Adventure|Sci-Fi,...,552.0,English,USA,PG-13,73000000.0,1997.0,506.0,6.5,1.85,0
530,Color,Steven Spielberg,151.0,128.0,14000.0,232.0,Chi McBride,15000.0,77032279.0,Comedy|Drama,...,596.0,English,USA,PG-13,60000000.0,2004.0,466.0,7.3,1.85,16000
539,Color,Steven Spielberg,298.0,163.0,14000.0,412.0,Moritz Bleibtreu,745.0,47379090.0,Drama|History|Thriller,...,824.0,English,France,R,70000000.0,2005.0,486.0,7.6,2.35,0
582,Color,Quentin Tarantino,486.0,153.0,16000.0,11000.0,Brad Pitt,13000.0,120523073.0,Adventure|Drama|War,...,1527.0,English,USA,R,75000000.0,2009.0,11000.0,8.3,2.35,42000
583,Color,Steven Spielberg,75.0,142.0,14000.0,5000.0,Julia Roberts,49000.0,119654900.0,Adventure|Comedy|Family|Fantasy,...,363.0,English,USA,PG,70000000.0,1991.0,8000.0,6.7,2.35,13000
597,Black and White,Steven Spielberg,388.0,146.0,14000.0,979.0,Benedict Cumberbatch,25000.0,79883359.0,Drama|War,...,488.0,English,USA,PG-13,66000000.0,2011.0,19000.0,7.2,2.35,28000
641,Color,Steven Spielberg,219.0,169.0,14000.0,13000.0,Vin Diesel,15000.0,216119491.0,Action|Drama|War,...,2277.0,English,USA,R,70000000.0,1998.0,14000.0,8.6,1.85,22000
646,Color,Steven Spielberg,538.0,150.0,14000.0,655.0,Hal Holbrook,23000.0,182204440.0,Biography|Drama|History|War,...,720.0,English,USA,PG-13,65000000.0,2012.0,826.0,7.4,2.35,71000
689,Color,Steven Spielberg,308.0,127.0,14000.0,191.0,Ariana Richards,967.0,356784000.0,Adventure|Sci-Fi|Thriller,...,895.0,English,USA,PG-13,63000000.0,1993.0,610.0,8.1,1.85,19000
698,Color,Quentin Tarantino,596.0,187.0,16000.0,1000.0,Jennifer Jason Leigh,46000.0,54116191.0,Crime|Drama|Mystery|Thriller|Western,...,1018.0,English,USA,R,44000000.0,2015.0,1000.0,7.9,2.76,114000
846,Black and White,Quentin Tarantino,354.0,111.0,16000.0,640.0,Vivica A. Fox,926.0,70098138.0,Action,...,2105.0,English,USA,R,30000000.0,2003.0,890.0,8.1,2.35,13000
849,Black and White,Quentin Tarantino,304.0,137.0,16000.0,348.0,Michael Parks,890.0,66207920.0,Action|Crime|Drama|Thriller,...,935.0,English,USA,R,30000000.0,2004.0,387.0,8.0,2.35,0
902,Color,Steven Spielberg,194.0,141.0,14000.0,3000.0,Tom Hanks,29000.0,164435221.0,Biography|Crime|Drama,...,667.0,English,USA,PG-13,52000000.0,2002.0,15000.0,8.0,1.85,15000
1030,Color,Steven Spielberg,149.0,127.0,14000.0,440.0,Julian Glover,11000.0,197171806.0,Action|Adventure|Fantasy,...,477.0,English,USA,PG-13,48000000.0,1989.0,844.0,8.3,2.35,0
1213,Color,Steven Spielberg,459.0,142.0,14000.0,423.0,Mark Rylance,15000.0,72306065.0,Drama|History|Thriller,...,355.0,English,USA,PG-13,40000000.0,2015.0,535.0,7.6,2.35,55000
1237,Color,Steven Spielberg,77.0,155.0,14000.0,11000.0,Morgan Freeman,12000.0,44175394.0,Drama|History,...,227.0,English,USA,R,36000000.0,1997.0,11000.0,7.2,1.85,0
1541,Color,Steven Spielberg,56.0,142.0,14000.0,642.0,John Belushi,16000.0,NaN,Action|Comedy|War,...,217.0,English,USA,PG,35000000.0,1979.0,1000.0,5.9,2.35,2000
1733,Color,Steven Spielberg,148.0,118.0,14000.0,237.0,Amrish Puri,11000.0,179870271.0,Action|Adventure,...,524.0,English,USA,PG,28000000.0,1984.0,429.0,7.6,2.35,0
1857,Black and White,Steven Spielberg,174.0,185.0,14000.0,212.0,Embeth Davidtz,14000.0,96067179.0,Biography|Drama|History,...,1273.0,English,USA,R,22000000.0,1993.0,795.0,8.9,1.85,41000
2128,Color,Steven Spielberg,234.0,115.0,14000.0,488.0,Karen Allen,11000.0,242374454.0,Action|Adventure,...,771.0,English,USA,PG,18000000.0,1981.0,783.0,8.5,2.35,16000
2130,Color,Steven Spielberg,171.0,135.0,14000.0,252.0,Teri Garr,559.0,128300000.0,Drama|Sci-Fi,...,339.0,English,USA,PG,19400870.0,1977.0,481.0,7.7,2.35,0
2575,Color,Steven Spielberg,70.0,154.0,14000.0,271.0,Rae Dawn Chong,852.0,94175854.0,Drama,...,199.0,English,USA,PG-13,15000000.0,1985.0,581.0,7.8,1.85,6000
2870,Color,Steven Spielberg,385.0,130.0,14000.0,366.0,Robert Shaw,813.0,260000000.0,Adventure|Drama|Thriller,...,962.0,English,USA,PG,8000000.0,1975.0,559.0,8.0,2.35,21000
2883,Color,Quentin Tarantino,140.0,154.0,16000.0,889.0,Sid Haig,22000.0,39647595.0,Crime|Thriller,...,462.0,English,USA,R,12000000.0,1997.0,1000.0,7.5,1.85,0
3028,Color,Steven Spielberg,215.0,120.0,14000.0,548.0,Dee Wallace,861.0,434949459.0,Family|Sci-Fi,...,515.0,English,USA,PG,10500000.0,1982.0,725.0,7.9,1.85,34000
3295,Color,Quentin Tarantino,215.0,178.0,16000.0,857.0,Eric Stoltz,13000.0,107930000.0,Crime|Drama,...,2195.0,English,USA,R,8000000.0,1994.0,902.0,8.9,2.35,45000
4395,Color,Quentin Tarantino,173.0,99.0,16000.0,455.0,Steve Buscemi,16000.0,2812029.0,Crime|Drama|Thriller,...,931.0,English,USA,R,1200000.0,1992.0,12000.0,8.4,2.35,19000

In [17]:
# seleccionar solo las filas para las cuales la columna "director_name"
# es igual a "Steven Spielberg" y "imdb_score" es mayor a 8.5

df_ss_imdb = df.loc[(df['director_name']=='Steven Spielberg') & (df['imdb_score'] > 8.5)] 
df_ss_imdb

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
641,Color,Steven Spielberg,219.0,169.0,14000.0,13000.0,Vin Diesel,15000.0,216119491.0,Action|Drama|War,...,2277.0,English,USA,R,70000000.0,1998.0,14000.0,8.6,1.85,22000
1857,Black and White,Steven Spielberg,174.0,185.0,14000.0,212.0,Embeth Davidtz,14000.0,96067179.0,Biography|Drama|History,...,1273.0,English,USA,R,22000000.0,1993.0,795.0,8.9,1.85,41000

### 3. Seleccion de filas y columnas

podemos combinar los metodos vistos anteriormente para seleccionar porciones (filas, columnas) de un DataFrame
Las sintaxis a usar denpenden de si recurrimos al metodo `iloc` o al medoto `loc`:

- Con el metodo `iloc`. En este caso la sintaxis es -> df.iloc[idxs_filas, idxs_col]
- Con el metodo `loc`. En este caso la sintaxis es -> df.loc[nombre_fila, nombre_col]

In [18]:
# ejm 1: selecionar de las filas 3 a la 5 y de las columnas 2 a la 5

df_ejem1 = df.iloc[3:6, 2:6]
df_ejem1

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes
3,813.0,164.0,22000.0,23000.0
4,NaN,NaN,131.0,NaN
5,462.0,132.0,475.0,530.0

In [19]:
# ejem 2: seleccionar la misma porcion anterior (ejem 1) con loc
df_ejem2 = df.loc[3:5, 'num_critic_for_reviews':'actor_3_facebook_likes']
df_ejem2

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes
3,813.0,164.0,22000.0,23000.0
4,NaN,NaN,131.0,NaN
5,462.0,132.0,475.0,530.0

In [20]:
row_names = [3,4,5]
col_name = ['num_critic_for_reviews','duration','director_facebook_likes','actor_3_facebook_likes']
df_ejem2 = df.loc[row_names, col_name]
df_ejem2

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes
3,813.0,164.0,22000.0,23000.0
4,NaN,NaN,131.0,NaN
5,462.0,132.0,475.0,530.0

### 4. Modificacion de columnas y filas

In [21]:
# renombrar columnas: cambiar el nomnbre de la columna "duration" a "duration_(min)"
df_duration_mint = df.rename(columns={"duration":"duration_(min)"})
df_duration_mint

,color,director_name,num_critic_for_reviews,duration_(min),director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [22]:
# cambio usando inplace= True
df.rename(columns={"duration":"duration_(min)"}, inplace=True)

# df = df.rename(columns={"duration":"duration_(min)"})

In [23]:
df

,color,director_name,num_critic_for_reviews,duration_(min),director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [24]:
df = df.rename(columns={"duration_(min)":"duration"})

In [25]:
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [26]:
# eliminar columas con "drop"
# eliminar la columna "duration"

# df.drop(labels=['duration'], axis=1, inplace=True)
df_no_duration = df.drop(labels=['duration'], axis=1)
df_no_duration

,color,director_name,num_critic_for_reviews,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,Eric Mabius,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,Natalie Zea,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,Eva Boehnke,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,Alan Ruck,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,John August,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

Y podemos añadir columnas y filas al DataFrame

In [27]:
df['calc'] = df['gross'] - df['budget']
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,calc
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000,523505847.0
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0,9404152.0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000,-44925825.0
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000,198130642.0
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84,NaN
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000,NaN
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16,NaN
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660,NaN
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456,84122.0