# Formas de ordenar un DataFrame

- Orgamizar las columnas del DataFrame
- Organizar las filas de DataFrame con base en la informacion contenida en una o multiples columnas
- Organizar las filas con base en el indice del DataFrame

### 1. Organizar las columnas del DataFrame

In [25]:
import pandas as pd

df = pd.read_csv('../data/peliculas.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [26]:
df.dtypes

color                            str
director_name                    str
num_critic_for_reviews       float64
duration                     float64
director_facebook_likes      float64
actor_3_facebook_likes       float64
actor_2_name                     str
actor_1_facebook_likes       float64
gross                        float64
genres                           str
actor_1_name                     str
movie_title                      str
num_voted_users                int64
cast_total_facebook_likes      int64
actor_3_name                     str
facenumber_in_poster         float64
plot_keywords                    str
movie_imdb_link                  str
num_user_for_reviews         float64
language                         str
country                          str
content_rating                   str
budget                       float64
title_year                   float64
actor_2_facebook_likes       float64
imdb_score                   float64
aspect_ratio                 float64
movie_facebook_likes           int64
dtype: object

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   str
 1   director_name              4814 non-null   str
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   str
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   str
 10  actor_1_name               4909 non-null   str
 11  movie_title                4916 non-null   str
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   str
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   str
 17  movie_imdb_link            4916 non-null   str
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4902 non-null   str
 20  country                    4911 non-null   str
 21  content_rating             4616 non-null   str
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), str(12)
memory usage: 1.1 MB

In [28]:
# agrupar las columnas en categoricas y numericas

# columnas categoricas
cols_cat = ['color', 'director_name', 'actor_2_name', 'genres', 'actor_1_name', 'movie_title', 
            'actor_3_name', 'plot_keywords', 'movie_imdb_link', 'language']
# columnas numericas
cols_num = ['num_critic_for_reviews','duration', 'director_facebook_likes', 'actor_3_facebook_likes',
 'actor_1_facebook_likes', 'gross', 'num_voted_users', 'cast_total_facebook_likes', 'facenumber_in_poster', 
 'num_user_for_reviews', 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

col_order = cols_cat + cols_num
print(col_order)

['color', 'director_name', 'actor_2_name', 'genres', 'actor_1_name', 'movie_title', 'actor_3_name', 'plot_keywords', 'movie_imdb_link', 'language', 'num_critic_for_reviews', 'duration', 'director_facebook_likes', 'actor_3_facebook_likes', 'actor_1_facebook_likes', 'gross', 'num_voted_users', 'cast_total_facebook_likes', 'facenumber_in_poster', 'num_user_for_reviews', 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

In [29]:
df = df[col_order]
df

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,...,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,Joel David Moore,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,Wes Studi,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,English,...,886204,4834,0.0,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,Orlando Bloom,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,Jack Davenport,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,English,...,471220,48350,0.0,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,Rory Kinnear,Action|Adventure|Thriller,Christoph Waltz,Spectre,Stephanie Sigman,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,English,...,275868,11700,1.0,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,Christian Bale,Action|Thriller,Tom Hardy,The Dark Knight Rises,Joseph Gordon-Levitt,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,English,...,1144337,106759,0.0,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,Rob Walker,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens,NaN,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,...,8,143,0.0,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,Daphne Zuniga,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,Crystal Lowe,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,English,...,629,2283,2.0,6.0,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,Valorie Curry,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,Sam Underwood,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,English,...,73839,1753,1.0,359.0,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,Maxwell Moody,Drama|Horror|Thriller,Eva Boehnke,A Plague So Pleasant,David Chandler,NaN,http://www.imdb.com/title/tt2107644/?ref_=fn_t...,English,...,38,0,0.0,3.0,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,Daniel Henney,Comedy|Drama|Romance,Alan Ruck,Shanghai Calling,Eliza Coupe,NaN,http://www.imdb.com/title/tt2070597/?ref_=fn_t...,English,...,1255,2386,5.0,9.0,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,Brian Herzlinger,Documentary,John August,My Date with Drew,Jon Gunn,actress name in title|crush|date|four word tit...,http://www.imdb.com/title/tt0378407/?ref_=fn_t...,English,...,4285,163,0.0,84.0,1100.0,2004.0,23.0,6.6,1.85,456

### 2. Ordenar las filas con base en los valores de una o multiple columnas

In [30]:
# ordenar el dataframe con base a la columna "movie_title" alfabeticamente
df_sorted_movie = df.sort_values(by='movie_title')
df_sorted_movie

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,...,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4349,Color,Tara Subkoff,Balthazar Getty,Drama|Horror|Mystery|Thriller,Timothy Hutton,#Horror,Lydia Hearst,bullying|cyberbullying|girl|internet|throat sl...,http://www.imdb.com/title/tt3526286/?ref_=fn_t...,English,...,1547,1044,1.0,42.0,1500000.0,2015.0,418.0,3.3,NaN,750
3629,Color,Dan Trachtenberg,John Gallagher Jr.,Drama|Horror|Mystery|Sci-Fi|Thriller,Bradley Cooper,10 Cloverfield Lane,Sumalee Montano,alien|bunker|car crash|kidnapping|minimal cast,http://www.imdb.com/title/tt1179933/?ref_=fn_t...,English,...,126893,14504,0.0,440.0,15000000.0,2016.0,338.0,7.3,2.35,33000
2964,Color,Timothy Hines,Kelly LeBrock,Drama,Christopher Lambert,10 Days in a Madhouse,Alexandra Callas,NaN,http://www.imdb.com/title/tt3453052/?ref_=fn_t...,English,...,314,2059,1.0,10.0,12000000.0,2015.0,445.0,7.5,1.85,26000
2799,Color,Gil Junger,Heath Ledger,Comedy|Drama|Romance,Joseph Gordon-Levitt,10 Things I Hate About You,Andrew Keegan,dating|protective father|school|shrew|teen movie,http://www.imdb.com/title/tt0147800/?ref_=fn_t...,English,...,222099,37907,6.0,549.0,16000000.0,1999.0,13000.0,7.2,1.85,10000
276,NaN,Christopher Barnard,NaN,Comedy,Mathew Buck,"10,000 B.C.",NaN,NaN,http://www.imdb.com/title/tt1869849/?ref_=fn_t...,NaN,...,6,5,0.0,NaN,NaN,NaN,NaN,7.2,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3597,Color,Jaume Balagueró,Pablo Rosso,Horror,Jonathan D. Mellor,[Rec] 2,Andrea Ros,apartment|apartment building|blood sample|cruc...,http://www.imdb.com/title/tt1245112/?ref_=fn_t...,Spanish,...,55597,73,0.0,148.0,5600000.0,2009.0,9.0,6.6,1.85,4000
2127,Color,David Cronenberg,Sarah Polley,Horror|Sci-Fi|Thriller,Jennifer Jason Leigh,eXistenZ,Callum Rennie,assassin|game|game designer|pod|virtual reality,http://www.imdb.com/title/tt0120907/?ref_=fn_t...,English,...,77493,2990,0.0,527.0,31000000.0,1999.0,900.0,6.8,1.85,6000
579,Color,Rob Cohen,Eve,Action|Adventure|Thriller,Vin Diesel,xXx,Leila Arcieri,agent|nsa|nsa agent|prague|russian,http://www.imdb.com/title/tt0295701/?ref_=fn_t...,English,...,142569,14790,0.0,737.0,70000000.0,2002.0,223.0,5.8,2.35,10000
782,Color,Lee Tamahori,Nona Gaye,Action|Adventure|Crime|Thriller,Sunny Mabrey,xXx: State of the Union,Xzibit,coup d'etat|mutiny|president|u.s. navy|washing...,http://www.imdb.com/title/tt0329774/?ref_=fn_t...,English,...,51349,993,2.0,213.0,87000000.0,2005.0,233.0,4.3,2.35,0
873,Color,Karyn Kusama,Sophie Okonedo,Action|Sci-Fi,Charlize Theron,Æon Flux,Paterson Joseph,based on cult favorite|disease|female hero|fem...,http://www.imdb.com/title/tt0402022/?ref_=fn_t...,English,...,110614,10185,0.0,532.0,62000000.0,2005.0,460.0,5.5,2.35,0

In [31]:
# ordenar el dataframe con base a la columna "movie_title" alfabeticamente inverso
df_sorted_movie = df.sort_values(by='movie_title', ascending=False)
df_sorted_movie

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,...,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
873,Color,Karyn Kusama,Sophie Okonedo,Action|Sci-Fi,Charlize Theron,Æon Flux,Paterson Joseph,based on cult favorite|disease|female hero|fem...,http://www.imdb.com/title/tt0402022/?ref_=fn_t...,English,...,110614,10185,0.0,532.0,62000000.0,2005.0,460.0,5.5,2.35,0
782,Color,Lee Tamahori,Nona Gaye,Action|Adventure|Crime|Thriller,Sunny Mabrey,xXx: State of the Union,Xzibit,coup d'etat|mutiny|president|u.s. navy|washing...,http://www.imdb.com/title/tt0329774/?ref_=fn_t...,English,...,51349,993,2.0,213.0,87000000.0,2005.0,233.0,4.3,2.35,0
579,Color,Rob Cohen,Eve,Action|Adventure|Thriller,Vin Diesel,xXx,Leila Arcieri,agent|nsa|nsa agent|prague|russian,http://www.imdb.com/title/tt0295701/?ref_=fn_t...,English,...,142569,14790,0.0,737.0,70000000.0,2002.0,223.0,5.8,2.35,10000
2127,Color,David Cronenberg,Sarah Polley,Horror|Sci-Fi|Thriller,Jennifer Jason Leigh,eXistenZ,Callum Rennie,assassin|game|game designer|pod|virtual reality,http://www.imdb.com/title/tt0120907/?ref_=fn_t...,English,...,77493,2990,0.0,527.0,31000000.0,1999.0,900.0,6.8,1.85,6000
3597,Color,Jaume Balagueró,Pablo Rosso,Horror,Jonathan D. Mellor,[Rec] 2,Andrea Ros,apartment|apartment building|blood sample|cruc...,http://www.imdb.com/title/tt1245112/?ref_=fn_t...,Spanish,...,55597,73,0.0,148.0,5600000.0,2009.0,9.0,6.6,1.85,4000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
276,NaN,Christopher Barnard,NaN,Comedy,Mathew Buck,"10,000 B.C.",NaN,NaN,http://www.imdb.com/title/tt1869849/?ref_=fn_t...,NaN,...,6,5,0.0,NaN,NaN,NaN,NaN,7.2,NaN,0
2799,Color,Gil Junger,Heath Ledger,Comedy|Drama|Romance,Joseph Gordon-Levitt,10 Things I Hate About You,Andrew Keegan,dating|protective father|school|shrew|teen movie,http://www.imdb.com/title/tt0147800/?ref_=fn_t...,English,...,222099,37907,6.0,549.0,16000000.0,1999.0,13000.0,7.2,1.85,10000
2964,Color,Timothy Hines,Kelly LeBrock,Drama,Christopher Lambert,10 Days in a Madhouse,Alexandra Callas,NaN,http://www.imdb.com/title/tt3453052/?ref_=fn_t...,English,...,314,2059,1.0,10.0,12000000.0,2015.0,445.0,7.5,1.85,26000
3629,Color,Dan Trachtenberg,John Gallagher Jr.,Drama|Horror|Mystery|Sci-Fi|Thriller,Bradley Cooper,10 Cloverfield Lane,Sumalee Montano,alien|bunker|car crash|kidnapping|minimal cast,http://www.imdb.com/title/tt1179933/?ref_=fn_t...,English,...,126893,14504,0.0,440.0,15000000.0,2016.0,338.0,7.3,2.35,33000
4349,Color,Tara Subkoff,Balthazar Getty,Drama|Horror|Mystery|Thriller,Timothy Hutton,#Horror,Lydia Hearst,bullying|cyberbullying|girl|internet|throat sl...,http://www.imdb.com/title/tt3526286/?ref_=fn_t...,English,...,1547,1044,1.0,42.0,1500000.0,2015.0,418.0,3.3,NaN,750

In [32]:
df_budget_gross = df.sort_values(by=['budget', 'gross'], ascending=False)
df_budget_gross

,color,director_name,actor_2_name,genres,actor_1_name,movie_title,actor_3_name,plot_keywords,movie_imdb_link,language,...,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
3787,Color,Chan-wook Park,Yeong-ae Lee,Crime|Drama,Min-sik Choi,Lady Vengeance,Hye-jeong Kang,cake|christian|lesbian sex|oral sex|pregnant s...,http://www.imdb.com/title/tt0451094/?ref_=fn_t...,Korean,...,53508,907,0.0,131.0,4.200000e+09,2005.0,126.0,7.7,2.35,4000
2955,Color,Lajos Koltai,Péter Fancsikai,Drama|Romance|War,Marcell Nagy,Fateless,Bálint Péntek,bus|death|gay slur|hatred|jewish,http://www.imdb.com/title/tt0367082/?ref_=fn_t...,Hungarian,...,5603,11,0.0,45.0,2.500000e+09,2005.0,2.0,7.1,2.35,607
2294,Color,Hayao Miyazaki,Jada Pinkett Smith,Adventure|Animation|Fantasy,Minnie Driver,Princess Mononoke,Billy Crudup,anime|cult film|forest|princess|studio ghibli,http://www.imdb.com/title/tt0119698/?ref_=fn_t...,Japanese,...,221552,2710,0.0,570.0,2.400000e+09,1997.0,851.0,8.4,1.85,11000
2305,Color,Katsuhiro Ôtomo,Robin Atkin Downes,Action|Adventure|Animation|Family|Sci-Fi|Thriller,William Hootkins,Steamboy,Rosalind Ayres,19th century|ball|boy|inventor|steam,http://www.imdb.com/title/tt0348121/?ref_=fn_t...,Japanese,...,13727,991,1.0,79.0,2.127520e+09,2004.0,336.0,6.9,1.85,973
3361,Color,Katsuhiro Ôtomo,Takeshi Kusao,Action|Animation|Sci-Fi,Mitsuo Iwata,Akira,Tesshô Genda,based on manga|biker gang|gifted child|post th...,http://www.imdb.com/title/tt0094625/?ref_=fn_t...,Japanese,...,106160,28,0.0,430.0,1.100000e+09,1988.0,5.0,8.1,1.85,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4892,Color,Marcus Nispel,Brittany Curran,Horror|Mystery|Thriller,Ashley Tramonte,Exeter,Lindsay MacDonald,asylum|demon|party|secret|teenager,http://www.imdb.com/title/tt1945044/?ref_=fn_t...,English,...,3836,2679,0.0,33.0,NaN,2015.0,512.0,4.6,1.85,0
4903,Color,Tadeo Garcia,Michael Cortez,Drama,Tatiana Suarez-Pico,On the Downlow,Eric Ambriz,gang initiation|gunplay|hazing|latino|shakespe...,http://www.imdb.com/title/tt0390323/?ref_=fn_t...,English,...,156,62,2.0,3.0,NaN,2004.0,20.0,6.1,NaN,22
4905,Color,Ash Baron-Cohen,Stanley B. Herman,Crime|Drama,Peter Greene,Bang,James Noble,corruption|homeless|homeless man|motorcycle|ur...,http://www.imdb.com/title/tt0109266/?ref_=fn_t...,English,...,438,1186,1.0,14.0,NaN,1995.0,194.0,6.4,NaN,20
4911,Color,Scott Smith,Daphne Zuniga,Comedy|Drama,Eric Mabius,Signed Sealed Delivered,Crystal Lowe,fraud|postal worker|prison|theft|trial,http://www.imdb.com/title/tt3000844/?ref_=fn_t...,English,...,629,2283,2.0,6.0,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,Valorie Curry,Crime|Drama|Mystery|Thriller,Natalie Zea,The Following,Sam Underwood,cult|fbi|hideout|prison escape|serial killer,http://www.imdb.com/title/tt2071645/?ref_=fn_t...,English,...,73839,1753,1.0,359.0,NaN,NaN,593.0,7.5,16.00,32000

In [33]:
df_budget_gross[['budget','gross']]

            budget      gross
3787  4.200000e+09   211667.0
2955  2.500000e+09   195888.0
2294  2.400000e+09  2298191.0
2305  2.127520e+09   410388.0
3361  1.100000e+09   439162.0
...            ...        ...
4892           NaN        NaN
4903           NaN        NaN
4905           NaN        NaN
4911           NaN        NaN
4912           NaN        NaN

[4916 rows x 2 columns]

### 3. Organizas las filas del DataFrame con base en el indice

In [35]:
df_sort_idx = df_budget_gross.sort_index()
df_sort_idx[['gross', 'budget']]

            gross       budget
0     760505847.0  237000000.0
1     309404152.0  300000000.0
2     200074175.0  245000000.0
3     448130642.0  250000000.0
4             NaN          NaN
...           ...          ...
4911          NaN          NaN
4912          NaN          NaN
4913          NaN       1400.0
4914      10443.0          NaN
4915      85222.0       1100.0

[4916 rows x 2 columns]

In [36]:
df_sort_idx = df_budget_gross.sort_index(ascending=False)
df_sort_idx[['gross', 'budget']]

            gross       budget
4915      85222.0       1100.0
4914      10443.0          NaN
4913          NaN       1400.0
4912          NaN          NaN
4911          NaN          NaN
...           ...          ...
4             NaN          NaN
3     448130642.0  250000000.0
2     200074175.0  245000000.0
1     309404152.0  300000000.0
0     760505847.0  237000000.0

[4916 rows x 2 columns]