# Metodos basicos y operacones sobre un DataFrame

- Metodos que nos permiten obtener informacion general de un dataframe
- metodos para realizar operaciones matematicas y de sintesis (sumarizacion) de un dataframe
- el metodo `apply` que nos permite aplicar cualquier tipo de funcion al dataframe

### 1. Metodos que nos permiten obtener informacion general de un dataframe

In [1]:
import pandas as pd

df = pd.read_csv('../data/peliculas.csv')
df

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

El metodo `info()` nos permite imprimir en pantalla ifnormacion general sobre la cantidad de datos "nulos - no nulos" y el tipo de dato presentes en cada columna

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4916 entries, 0 to 4915
Data columns (total 28 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   color                      4897 non-null   str
 1   director_name              4814 non-null   str
 2   num_critic_for_reviews     4867 non-null   float64
 3   duration                   4901 non-null   float64
 4   director_facebook_likes    4814 non-null   float64
 5   actor_3_facebook_likes     4893 non-null   float64
 6   actor_2_name               4903 non-null   str
 7   actor_1_facebook_likes     4909 non-null   float64
 8   gross                      4054 non-null   float64
 9   genres                     4916 non-null   str
 10  actor_1_name               4909 non-null   str
 11  movie_title                4916 non-null   str
 12  num_voted_users            4916 non-null   int64
 13  cast_total_facebook_likes  4916 non-null   int64
 14  actor_3_name               4893 non-null   str
 15  facenumber_in_poster       4903 non-null   float64
 16  plot_keywords              4764 non-null   str
 17  movie_imdb_link            4916 non-null   str
 18  num_user_for_reviews       4895 non-null   float64
 19  language                   4902 non-null   str
 20  country                    4911 non-null   str
 21  content_rating             4616 non-null   str
 22  budget                     4432 non-null   float64
 23  title_year                 4810 non-null   float64
 24  actor_2_facebook_likes     4903 non-null   float64
 25  imdb_score                 4916 non-null   float64
 26  aspect_ratio               4590 non-null   float64
 27  movie_facebook_likes       4916 non-null   int64
dtypes: float64(13), int64(3), str(12)
memory usage: 1.1 MB

Los metodos `head()`, `tail()`, `sample()` nos permitir imprimir en pantalla las primeras filas del DataFrame, las ultimas filas o una seleccion aleatoria de filas respectivamente

In [7]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [8]:
df.head(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000
6,Color,Sam Raimi,392.0,156.0,0.0,4000.0,James Franco,24000.0,336530303.0,Action|Adventure|Romance,...,1902.0,English,USA,PG-13,258000000.0,2007.0,11000.0,6.2,2.35,0
7,Color,Nathan Greno,324.0,100.0,15.0,284.0,Donna Murphy,799.0,200807262.0,Adventure|Animation|Comedy|Family|Fantasy|Musi...,...,387.0,English,USA,PG,260000000.0,2010.0,553.0,7.8,1.85,29000
8,Color,Joss Whedon,635.0,141.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,2.35,118000
9,Color,David Yates,375.0,153.0,282.0,10000.0,Daniel Radcliffe,25000.0,301956980.0,Adventure|Family|Fantasy|Mystery,...,973.0,English,UK,PG,250000000.0,2009.0,11000.0,7.5,2.35,10000

In [6]:
df.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [9]:
df.tail(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4906,Color,Shane Carruth,143.0,77.0,291.0,8.0,David Sullivan,291.0,424760.0,Drama|Sci-Fi|Thriller,...,371.0,English,USA,PG-13,7000.0,2004.0,45.0,7.0,1.85,19000
4907,Color,Neill Dela Llana,35.0,80.0,0.0,0.0,Edgar Tancangco,0.0,70071.0,Thriller,...,35.0,English,Philippines,Not Rated,7000.0,2005.0,0.0,6.3,NaN,74
4908,Color,Robert Rodriguez,56.0,81.0,0.0,6.0,Peter Marquardt,121.0,2040920.0,Action|Crime|Drama|Romance|Thriller,...,130.0,Spanish,USA,R,7000.0,1992.0,20.0,6.9,1.37,0
4909,Color,Anthony Vallone,NaN,84.0,2.0,2.0,John Considine,45.0,NaN,Crime|Drama,...,1.0,English,USA,PG-13,3250.0,2005.0,44.0,7.8,NaN,4
4910,Color,Edward Burns,14.0,95.0,0.0,133.0,Caitlin FitzGerald,296.0,4584.0,Comedy|Drama,...,14.0,English,USA,Not Rated,9000.0,2011.0,205.0,6.4,NaN,413
4911,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
4912,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
4913,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
4914,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
4915,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

In [12]:
df.sample()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
1075,Color,Denis Villeneuve,454.0,153.0,777.0,1000.0,Jake Gyllenhaal,20000.0,60962878.0,Crime|Drama|Mystery|Thriller,...,620.0,English,USA,R,46000000.0,2013.0,15000.0,8.1,1.85,86000

In [13]:
df.sample(10)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
4580,Color,Joseph Kosinski,4.0,NaN,364.0,567.0,Lauren Cohan,22000.0,NaN,Action|Adventure|Fantasy|Sci-Fi,...,11.0,English,USA,NaN,NaN,2014.0,4000.0,8.1,NaN,1000
1040,Color,James Mangold,125.0,123.0,446.0,821.0,Natasha Lyonne,20000.0,47095453.0,Comedy|Fantasy|Romance,...,316.0,English,USA,PG-13,48000000.0,2001.0,1000.0,6.4,1.85,0
2729,Black and White,Jon Turteltaub,39.0,98.0,226.0,496.0,Leon,953.0,68856263.0,Adventure|Comedy|Family|Sport,...,97.0,English,USA,PG,15000000.0,1993.0,730.0,6.9,1.85,0
1539,Color,Joel Schumacher,224.0,98.0,541.0,897.0,Virginia Madsen,8000.0,35063732.0,Mystery|Thriller,...,383.0,English,USA,R,32000000.0,2007.0,912.0,6.4,2.35,10000
4169,Color,Alex Kendrick,34.0,129.0,589.0,341.0,Alex Kendrick,690.0,34522221.0,Drama,...,175.0,English,USA,PG-13,2000000.0,2011.0,589.0,7.0,2.35,10000
2401,Color,Nicholas Hytner,68.0,115.0,13.0,111.0,Susan May Pratt,757.0,17174870.0,Drama|Music|Romance,...,210.0,English,USA,PG-13,18000000.0,2000.0,220.0,6.7,2.35,0
1308,Color,Iain Softley,79.0,107.0,34.0,472.0,Fisher Stevens,11000.0,7564000.0,Comedy|Crime|Drama|Thriller,...,223.0,English,USA,PG-13,20000000.0,1995.0,922.0,6.2,2.35,12000
1188,Color,Ken Kwapis,161.0,129.0,42.0,49.0,Sabrina Revelle,97.0,93952276.0,Comedy|Drama|Romance,...,203.0,English,USA,PG-13,40000000.0,2009.0,50.0,6.4,2.35,12000
4498,Color,A. Raven Cruz,3.0,97.0,0.0,94.0,Vanilla Ice,639.0,NaN,Action|Adventure|Comedy|Fantasy|Sci-Fi,...,9.0,English,USA,R,1000000.0,2005.0,361.0,1.9,1.78,128
437,Color,Dean DeBlois,180.0,85.0,255.0,443.0,Jason Scott Lee,1000.0,145771527.0,Adventure|Animation|Comedy|Drama|Family|Fantas...,...,367.0,English,USA,PG,80000000.0,2002.0,533.0,7.2,1.66,0

El metodo `describe()` permite imprimir informacion estadistica de las columnas que contienen variables numericas

In [14]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4867.000000,4901.000000,4814.000000,4893.000000,4909.000000,4.054000e+03,4.916000e+03,4916.000000,4903.000000,4895.000000,4.432000e+03,4810.000000,4903.000000,4916.000000,4590.000000,4916.000000
mean,137.988905,107.090798,691.014541,631.276313,6494.488491,4.764451e+07,8.264492e+04,9579.815907,1.377320,267.668846,3.654749e+07,2002.447609,1621.923516,6.437429,2.222349,7348.294142
std,120.239379,25.286015,2832.954125,1625.874802,15106.986884,6.737255e+07,1.383222e+05,18164.316990,2.023826,372.934839,1.002427e+08,12.453977,4011.299523,1.127802,1.402940,19206.016458
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,49.000000,93.000000,7.000000,132.000000,607.000000,5.019656e+06,8.361750e+03,1394.750000,0.000000,64.000000,6.000000e+06,1999.000000,277.000000,5.800000,1.850000,0.000000
50%,108.000000,103.000000,48.000000,366.000000,982.000000,2.504396e+07,3.313250e+04,3049.000000,1.000000,153.000000,1.985000e+07,2005.000000,593.000000,6.600000,2.350000,159.000000
75%,191.000000,118.000000,189.750000,633.000000,11000.000000,6.110841e+07,9.377275e+04,13616.750000,2.000000,320.500000,4.300000e+07,2011.000000,912.000000,7.200000,2.350000,2000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,4.200000e+09,2016.000000,137000.000000,9.500000,16.000000,349000.000000

El metodo `value_counts()` tambien resulta util pues permite imprimir en pantalla el conteo de valores presentes en cada columna, funciona tanto para variables numericas como categoricas

In [15]:
df['duration'].value_counts()

duration
90.0     160
100.0    137
98.0     135
101.0    132
97.0     131
        ...
58.0       1
35.0       1
59.0       1
62.0       1
47.0       1
Name: count, Length: 191, dtype: int64

In [16]:
df['color'].value_counts()

color
Color              4693
Black and White     204
Name: count, dtype: int64

### 2. Operacones matematicas y de sintesis

- `min()` y `max()`: calcula el maximo / minimo de cada fila o columna
- `sum()`: calcula la suma de los elementos de cada fila o columna
- `mean()`, `std()`, `median()`: calcula la media/desviacion/mediana de cada fila o columna

In [17]:
df.min()

color                                                          Black and White
director_name                                                    A. Raven Cruz
num_critic_for_reviews                                                     1.0
duration                                                                   7.0
director_facebook_likes                                                    0.0
actor_3_facebook_likes                                                     0.0
actor_2_name                                                           50 Cent
actor_1_facebook_likes                                                     0.0
gross                                                                    162.0
genres                                                                  Action
actor_1_name                                                           50 Cent
movie_title                                                            #Horror
num_voted_users                                                              5
cast_total_facebook_likes                                                    0
actor_3_name                                                           50 Cent
facenumber_in_poster                                                       0.0
plot_keywords                         10 year old|dog|florida|girl|supermarket
movie_imdb_link              http://www.imdb.com/title/tt0006864/?ref_=fn_t...
num_user_for_reviews                                                       1.0
language                                                            Aboriginal
country                                                            Afghanistan
content_rating                                                        Approved
budget                                                                   218.0
title_year                                                              1916.0
actor_2_facebook_likes                                                     0.0
imdb_score                                                                 1.6
aspect_ratio                                                              1.18
movie_facebook_likes                                                         0
dtype: object

In [18]:
df['num_critic_for_reviews'].min()

np.float64(1.0)

In [22]:
cols_num = ['num_critic_for_reviews','duration', 'director_facebook_likes', 'actor_3_facebook_likes',
 'actor_1_facebook_likes', 'gross', 'num_voted_users', 'cast_total_facebook_likes', 'facenumber_in_poster', 
 'num_user_for_reviews', 'budget', 'title_year', 'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio', 'movie_facebook_likes']

In [20]:
df.select_dtypes(include='number').min()

num_critic_for_reviews          1.00
duration                        7.00
director_facebook_likes         0.00
actor_3_facebook_likes          0.00
actor_1_facebook_likes          0.00
gross                         162.00
num_voted_users                 5.00
cast_total_facebook_likes       0.00
facenumber_in_poster            0.00
num_user_for_reviews            1.00
budget                        218.00
title_year                   1916.00
actor_2_facebook_likes          0.00
imdb_score                      1.60
aspect_ratio                    1.18
movie_facebook_likes            0.00
dtype: float64

In [23]:
df.select_dtypes(include='number').std()

num_critic_for_reviews       1.202394e+02
duration                     2.528602e+01
director_facebook_likes      2.832954e+03
actor_3_facebook_likes       1.625875e+03
actor_1_facebook_likes       1.510699e+04
gross                        6.737255e+07
num_voted_users              1.383222e+05
cast_total_facebook_likes    1.816432e+04
facenumber_in_poster         2.023826e+00
num_user_for_reviews         3.729348e+02
budget                       1.002427e+08
title_year                   1.245398e+01
actor_2_facebook_likes       4.011300e+03
imdb_score                   1.127802e+00
aspect_ratio                 1.402940e+00
movie_facebook_likes         1.920602e+04
dtype: float64

In [ ]:
dir(df)

'abs',
 'actor_1_facebook_likes',
 'actor_1_name',
 'actor_2_facebook_likes',
 'actor_2_name',
 'actor_3_facebook_likes',
 'actor_3_name',
 'add',
 'add_prefix',
 'add_suffix',
 'agg',
 'aggregate',
 'align',
 'all',
 'any',
 'apply',
 'asfreq',
 'asof',
 'aspect_ratio',
 'assign',
 'astype',
 'at',
 'at_time',
 'attrs',
 'axes',
 'between_time',
 'bfill',
 'boxplot',
 'budget',
 'cast_total_facebook_likes',
 'clip',
 'color',
 'columns',
 'combine',
 'combine_first',
 'compare',
 'content_rating',
 'convert_dtypes',
 'copy',
 'corr',
 'corrwith',
 'count',
 'country',
 'cov',
 'cummax',
 'cummin',
 'cumprod',
 'cumsum',
 'describe',
 'diff',
 'director_facebook_likes',
 'director_name',
 'div',
 'divide',
 'dot',
 'drop',
 'drop_duplicates',
 'droplevel',
 'dropna',
 'dtypes',
 'duplicated',
 'duration',
 'empty',
 'eq',
 'equals',
 'eval',
 'ewm',
 'expanding',
 'explode',
 'facenumber_in_poster',
 'ffill',
 'fillna',
 'filter',
 'first_valid_index',
 'flags',
 'floordiv',
 'from_arrow',
 'from_dict',
 'from_records',
 'ge',
 'genres',
 'get',
 'gross',
 'groupby',
 'gt',
 'head',
 'hist',
 'iat',
 'idxmax',
 'idxmin',
 'iloc',
 'imdb_score',
 'index',
 'infer_objects',
 'info',
 'insert',
 'interpolate',
 'isetitem',
 'isin',
 'isna',
 'isnull',
 'items',
 'iterrows',
 'itertuples',
 'join',
 'keys',
 'kurt',
 'kurtosis',
 'language',
 'last_valid_index',
 'le',
 'loc',
 'lt',
 'map',
 'mask',
 'max',
 'mean',
 'median',
 'melt',
 'memory_usage',
 'merge',
 'min',
 'mod',
 'mode',
 'movie_facebook_likes',
 'movie_imdb_link',
 'movie_title',
 'mul',
 'multiply',
 'ndim',
 'ne',
 'nlargest',
 'notna',
 'notnull',
 'nsmallest',
 'num_critic_for_reviews',
 'num_user_for_reviews',
 'num_voted_users',
 'nunique',
 'pct_change',
 'pipe',
 'pivot',
 'pivot_table',
 'plot',
 'plot_keywords',
 'pop',
 'pow',
 'prod',
 'product',
 'quantile',
 'query',
 'radd',
 'rank',
 'rdiv',
 'reindex',
 'reindex_like',
 'rename',
 'rename_axis',
 'reorder_levels',
 'replace',
 'resample',
 'reset_index',
 'rfloordiv',
 'rmod',
 'rmul',
 'rolling',
 'round',
 'rpow',
 'rsub',
 'rtruediv',
 'sample',
 'select_dtypes',
 'sem',
 'set_axis',
 'set_flags',
 'set_index',
 'shape',
 'shift',
 'size',
 'skew',
 'sort_index',
 'sort_values',
 'squeeze',
 'stack',
 'std',
 'style',
 'sub',
 'subtract',
 'sum',
 'swaplevel',
 'tail',
 'take',
 'title_year',
 'to_clipboard',
 'to_csv',
 'to_dict',
 'to_excel',
 'to_feather',
 'to_hdf',
 'to_html',
 'to_iceberg',
 'to_json',
 'to_latex',
 'to_markdown',
 'to_numpy',
 'to_orc',
 'to_parquet',
 'to_period',
 'to_pickle',
 'to_records',
 'to_sql',
 'to_stata',
 'to_string',
 'to_timestamp',
 'to_xarray',
 'to_xml',
 'transform',
 'transpose',
 'truediv',
 'truncate',
 'tz_convert',
 'tz_localize',
 'unstack',
 'update',
 'value_counts',
 'values',
 'var',
 'where',
 'xs'

### 3. Apply: aplicar una funcion especifica por filas o columas

In [26]:
import numpy as np

df.select_dtypes(include='number').apply(np.sqrt)

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,26.888659,13.341664,0.000000,29.240383,31.622777,27577.270478,941.384087,69.526973,0.000000,55.263008,15394.804318,44.821870,30.594117,2.810694,1.334166,181.659021
1,17.378147,13.000000,23.727621,31.622777,200.000000,17589.887777,686.454660,219.886334,0.000000,35.185224,17320.508076,44.799554,70.710678,2.664583,1.532971,0.000000
2,24.535688,12.165525,0.000000,12.688578,104.880885,14144.757863,525.231378,108.166538,1.000000,31.527766,15652.475842,44.888751,19.824228,2.607681,1.532971,291.547595
3,28.513155,12.806248,148.323970,151.657509,164.316767,21169.096391,1069.736884,326.739958,0.000000,51.971146,15811.388301,44.855323,151.657509,2.915476,1.532971,404.969135
4,NaN,NaN,11.445523,NaN,11.445523,NaN,2.828427,11.958261,0.000000,NaN,NaN,NaN,3.464102,2.664583,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,1.000000,9.327379,1.414214,17.832555,25.238859,NaN,25.079872,47.780749,1.414214,2.449490,NaN,44.866469,21.679483,2.774887,NaN,9.165151
4912,6.557439,6.557439,NaN,17.860571,29.000000,NaN,271.733325,41.868843,1.000000,18.947295,NaN,NaN,24.351591,2.738613,4.000000,178.885438
4913,3.605551,8.717798,0.000000,0.000000,0.000000,NaN,6.164414,0.000000,0.000000,1.732051,37.416574,44.866469,0.000000,2.509980,NaN,4.000000
4914,3.741657,10.000000,0.000000,22.113344,30.757113,102.190998,35.425979,48.846699,2.236068,3.000000,NaN,44.855323,26.814175,2.509980,1.532971,25.690465
4915,6.557439,9.486833,4.000000,4.000000,9.273618,291.928073,65.459911,12.767145,0.000000,9.165151,33.166248,44.766059,4.795832,2.569047,1.360147,21.354157

In [27]:
df['duration'].apply(np.sqrt)

0       13.341664
1       13.000000
2       12.165525
3       12.806248
4             NaN
          ...
4911     9.327379
4912     6.557439
4913     8.717798
4914    10.000000
4915     9.486833
Name: duration, Length: 4916, dtype: float64

In [28]:
df[['duration','gross']].apply(np.sqrt)

       duration         gross
0     13.341664  27577.270478
1     13.000000  17589.887777
2     12.165525  14144.757863
3     12.806248  21169.096391
4           NaN           NaN
...         ...           ...
4911   9.327379           NaN
4912   6.557439           NaN
4913   8.717798           NaN
4914  10.000000    102.190998
4915   9.486833    291.928073

[4916 rows x 2 columns]

In [29]:
df['genres']

0       Action|Adventure|Fantasy|Sci-Fi
1              Action|Adventure|Fantasy
2             Action|Adventure|Thriller
3                       Action|Thriller
4                           Documentary
                     ...
4911                       Comedy|Drama
4912       Crime|Drama|Mystery|Thriller
4913              Drama|Horror|Thriller
4914               Comedy|Drama|Romance
4915                        Documentary
Name: genres, Length: 4916, dtype: str

In [30]:
def change_str(string):
    if "|" in string:
        return string.replace("|", ", ")

In [31]:
df['genres'].apply(change_str)

0       Action, Adventure, Fantasy, Sci-Fi
1               Action, Adventure, Fantasy
2              Action, Adventure, Thriller
3                         Action, Thriller
4                                      NaN
                       ...
4911                         Comedy, Drama
4912       Crime, Drama, Mystery, Thriller
4913               Drama, Horror, Thriller
4914                Comedy, Drama, Romance
4915                                   NaN
Name: genres, Length: 4916, dtype: str