# Creacion y Almacenamiento de DataFrames

- como crear desde cero un dataframe a partir de un diccionario en Python
- como crer un DataFrame a partir de un JSON y como almacenar un dataframe en formato JSON
- como crear un archivo de excel de uno o multiples dataframes y como crear dataframes a partir de archivos excel

### 1. Creacion de un DataFrame a partir de un diccionario

In [2]:
# paso 1: crear el diccionario
ciudades = {
    'Ciudad':['Paris','Milan','New York','Londres'],
    'Pais':['Francia','Italia','Estados Unidos','Inglaterra'],
    'Poblacion':[2161000,1352000,8468000,8982000]
}

for clave, valor in ciudades.items():
    print(f"{clave}: {valor}")

Ciudad: ['Paris', 'Milan', 'New York', 'Londres']
Pais: ['Francia', 'Italia', 'Estados Unidos', 'Inglaterra']
Poblacion: [2161000, 1352000, 8468000, 8982000]

In [3]:
# paso 2: crear el dataframe
import pandas as pd

df_ciudades = pd.DataFrame(ciudades)
df_ciudades

     Ciudad            Pais  Poblacion
0     Paris         Francia    2161000
1     Milan          Italia    1352000
2  New York  Estados Unidos    8468000
3   Londres      Inglaterra    8982000

### 2. Creacion de un DataFrame a partir de un archivo JSON

In [4]:
# Leer JSON directamente con pandas

df_json = pd.read_json('../data/stations.json')
df_json

              executionTime                                    stationBeanList
0    2016-01-22 04:32:49 PM  {'id': 72, 'stationName': 'W 52 St & 11 Ave', ...
1    2016-01-22 04:32:49 PM  {'id': 79, 'stationName': 'Franklin St & W Bro...
2    2016-01-22 04:32:49 PM  {'id': 82, 'stationName': 'St James Pl & Pearl...
3    2016-01-22 04:32:49 PM  {'id': 83, 'stationName': 'Atlantic Ave & Fort...
4    2016-01-22 04:32:49 PM  {'id': 116, 'stationName': 'W 17 St & 8 Ave', ...
..                      ...                                                ...
504  2016-01-22 04:32:49 PM  {'id': 3238, 'stationName': 'E 80 St & 2 Ave',...
505  2016-01-22 04:32:49 PM  {'id': 3241, 'stationName': 'Monroe St & Tompk...
506  2016-01-22 04:32:49 PM  {'id': 3242, 'stationName': 'Schermerhorn St &...
507  2016-01-22 04:32:49 PM  {'id': 3243, 'stationName': 'E 58 St & 1 Ave',...
508  2016-01-22 04:32:49 PM  {'id': 3244, 'stationName': 'University Pl & E...

[509 rows x 2 columns]

In [5]:
type(df_json)

pandas.DataFrame

In [6]:
df_json.keys()

Index(['executionTime', 'stationBeanList'], dtype='str')

In [7]:
# nos interesa el key "stationBeanList" donde se encuentra la informacion de interes por cada estacion

df_json['stationBeanList']

0      {'id': 72, 'stationName': 'W 52 St & 11 Ave', ...
1      {'id': 79, 'stationName': 'Franklin St & W Bro...
2      {'id': 82, 'stationName': 'St James Pl & Pearl...
3      {'id': 83, 'stationName': 'Atlantic Ave & Fort...
4      {'id': 116, 'stationName': 'W 17 St & 8 Ave', ...
                             ...
504    {'id': 3238, 'stationName': 'E 80 St & 2 Ave',...
505    {'id': 3241, 'stationName': 'Monroe St & Tompk...
506    {'id': 3242, 'stationName': 'Schermerhorn St &...
507    {'id': 3243, 'stationName': 'E 58 St & 1 Ave',...
508    {'id': 3244, 'stationName': 'University Pl & E...
Name: stationBeanList, Length: 509, dtype: object

In [8]:
df_json = pd.read_json('../data/stations.json')['stationBeanList']
df_json

0      {'id': 72, 'stationName': 'W 52 St & 11 Ave', ...
1      {'id': 79, 'stationName': 'Franklin St & W Bro...
2      {'id': 82, 'stationName': 'St James Pl & Pearl...
3      {'id': 83, 'stationName': 'Atlantic Ave & Fort...
4      {'id': 116, 'stationName': 'W 17 St & 8 Ave', ...
                             ...
504    {'id': 3238, 'stationName': 'E 80 St & 2 Ave',...
505    {'id': 3241, 'stationName': 'Monroe St & Tompk...
506    {'id': 3242, 'stationName': 'Schermerhorn St &...
507    {'id': 3243, 'stationName': 'E 58 St & 1 Ave',...
508    {'id': 3244, 'stationName': 'University Pl & E...
Name: stationBeanList, Length: 509, dtype: object

In [9]:
df_estaciones = pd.json_normalize(df_json)
df_estaciones

,id,stationName,availableDocks,totalDocks,latitude,longitude,statusValue,statusKey,availableBikes,stAddress1,stAddress2,city,postalCode,location,altitude,testStation,lastCommunicationTime,landMark
0,72,W 52 St & 11 Ave,32,39,40.767272,-73.993929,In Service,1,7,W 52 St & 11 Ave,,,,,,False,2016-01-22 04:30:15 PM,
1,79,Franklin St & W Broadway,0,33,40.719116,-74.006667,In Service,1,33,Franklin St & W Broadway,,,,,,False,2016-01-22 04:32:41 PM,
2,82,St James Pl & Pearl St,27,27,40.711174,-74.000165,In Service,1,0,St James Pl & Pearl St,,,,,,False,2016-01-22 04:29:41 PM,
3,83,Atlantic Ave & Fort Greene Pl,21,62,40.683826,-73.976323,In Service,1,40,Atlantic Ave & Fort Greene Pl,,,,,,False,2016-01-22 04:32:33 PM,
4,116,W 17 St & 8 Ave,19,39,40.741776,-74.001497,In Service,1,19,W 17 St & 8 Ave,,,,,,False,2016-01-22 04:32:32 PM,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,3238,E 80 St & 2 Ave,35,37,40.773914,-73.954395,In Service,1,2,E 80 St & 2 Ave,,,,,,False,2016-01-22 04:30:37 PM,
505,3241,Monroe St & Tompkins Ave,18,19,40.686203,-73.944694,In Service,1,1,Monroe St & Tompkins Ave,,,,,,False,2016-01-22 04:30:38 PM,
506,3242,Schermerhorn St & Court St,5,39,40.691029,-73.991834,In Service,1,31,Schermerhorn St & Court St,,,,,,False,2016-01-22 04:31:33 PM,
507,3243,E 58 St & 1 Ave,28,29,40.758924,-73.962262,In Service,1,1,E 58 St & 1 Ave,,,,,,False,2016-01-22 04:30:05 PM,
508,3244,University Pl & E 8 St,27,31,40.731437,-73.994903,In Service,1,4,University Pl & E 8 St,,,,,,False,2016-01-22 04:31:18 PM,

##### Diccionario de datos Stations.json

- *id* y *stationName*: número identificador y nombre de cada estación
- *availableDocks*: número de puestos disponibles para el parqueo de bicicletas
- *totalDocks*: número total de puestos para el parqueo de bicicletas
- *latitude*, *longitud*: coordenadas geográficas de la estación
- *statusValue*, *statusKey*: indican si la estación está funcionando (*In Service*, 1) o no. Para el caso de este archivo **todas** las estaciones están prestando servicio
- *availableBikes*: cantidad de bicicletas disponibles
- *stAddress1*, *stAddress2*: dirección donde se encuentra ubicada la estación
- *testStation*: indica si se trata de una estación de prueba. En todos los casos este valor es *false*
- *lastCommunicationTime*: fecha y hora en la que se obtuvo la última actualización de la estación
- *city*, *postalCode*, *location*, *altitude*, *landMark*: campos no usados

### 3. Almacenamiento de un DataFrame a formato JSON

In [10]:
# Almacenar el DataFrame como archivo JSON

df_estaciones.to_json('../data/station_from_df.json')

In [11]:
df_from_json = pd.read_json('../data/station_from_df.json')
df_from_json

,id,stationName,availableDocks,totalDocks,latitude,longitude,statusValue,statusKey,availableBikes,stAddress1,stAddress2,city,postalCode,location,altitude,testStation,lastCommunicationTime,landMark
0,72,W 52 St & 11 Ave,32,39,40.767272,-73.993929,In Service,1,7,W 52 St & 11 Ave,,,,,,False,2016-01-22 04:30:15 PM,
1,79,Franklin St & W Broadway,0,33,40.719116,-74.006667,In Service,1,33,Franklin St & W Broadway,,,,,,False,2016-01-22 04:32:41 PM,
2,82,St James Pl & Pearl St,27,27,40.711174,-74.000165,In Service,1,0,St James Pl & Pearl St,,,,,,False,2016-01-22 04:29:41 PM,
3,83,Atlantic Ave & Fort Greene Pl,21,62,40.683826,-73.976323,In Service,1,40,Atlantic Ave & Fort Greene Pl,,,,,,False,2016-01-22 04:32:33 PM,
4,116,W 17 St & 8 Ave,19,39,40.741776,-74.001497,In Service,1,19,W 17 St & 8 Ave,,,,,,False,2016-01-22 04:32:32 PM,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,3238,E 80 St & 2 Ave,35,37,40.773914,-73.954395,In Service,1,2,E 80 St & 2 Ave,,,,,,False,2016-01-22 04:30:37 PM,
505,3241,Monroe St & Tompkins Ave,18,19,40.686203,-73.944694,In Service,1,1,Monroe St & Tompkins Ave,,,,,,False,2016-01-22 04:30:38 PM,
506,3242,Schermerhorn St & Court St,5,39,40.691029,-73.991834,In Service,1,31,Schermerhorn St & Court St,,,,,,False,2016-01-22 04:31:33 PM,
507,3243,E 58 St & 1 Ave,28,29,40.758924,-73.962262,In Service,1,1,E 58 St & 1 Ave,,,,,,False,2016-01-22 04:30:05 PM,
508,3244,University Pl & E 8 St,27,31,40.731437,-73.994903,In Service,1,4,University Pl & E 8 St,,,,,,False,2016-01-22 04:31:18 PM,

### 4. Almacenamiento en formato Excel

Pandas provee 2 funciones para el almacenamiento de este tipo de archivoss: `to_exel`, `ExcelWriter`

primero denemos instalar la libreria "`openpyxl`"

`pip install openpyxl` -> (entorno local)

`!pip install openpyxl` -> (google colab)

In [13]:
# almacenamos el df que acabamos de crear (df_from_json) en la hoja de calculo
# estaciones_ciudades.xlsx  y en la hoja "estaciones"
df_from_json.to_excel('../data/estaciones_ciudades.xlsx', sheet_name="estaciones", index=False)

In [14]:
df_from_json.to_excel('../data/estaciones_ciudades.xlsx', sheet_name="ciudades", index=False)

In [16]:
with pd.ExcelWriter('../data/stations_cities.xlsx') as writer:
    df_from_json.to_excel(writer, sheet_name="estaciones", index=False)
    df_ciudades.to_excel(writer, sheet_name="ciudades", index=False)

### 5. Lectura de archivos en formato Excel

In [18]:
df_stations = pd.read_excel('../data/stations_cities.xlsx', sheet_name='estaciones')
df_stations

,id,stationName,availableDocks,totalDocks,latitude,longitude,statusValue,statusKey,availableBikes,stAddress1,stAddress2,city,postalCode,location,altitude,testStation,lastCommunicationTime,landMark
0,72,W 52 St & 11 Ave,32,39,40.767272,-73.993929,In Service,1,7,W 52 St & 11 Ave,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:30:15 PM,NaN
1,79,Franklin St & W Broadway,0,33,40.719116,-74.006667,In Service,1,33,Franklin St & W Broadway,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:32:41 PM,NaN
2,82,St James Pl & Pearl St,27,27,40.711174,-74.000165,In Service,1,0,St James Pl & Pearl St,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:29:41 PM,NaN
3,83,Atlantic Ave & Fort Greene Pl,21,62,40.683826,-73.976323,In Service,1,40,Atlantic Ave & Fort Greene Pl,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:32:33 PM,NaN
4,116,W 17 St & 8 Ave,19,39,40.741776,-74.001497,In Service,1,19,W 17 St & 8 Ave,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:32:32 PM,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
504,3238,E 80 St & 2 Ave,35,37,40.773914,-73.954395,In Service,1,2,E 80 St & 2 Ave,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:30:37 PM,NaN
505,3241,Monroe St & Tompkins Ave,18,19,40.686203,-73.944694,In Service,1,1,Monroe St & Tompkins Ave,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:30:38 PM,NaN
506,3242,Schermerhorn St & Court St,5,39,40.691029,-73.991834,In Service,1,31,Schermerhorn St & Court St,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:31:33 PM,NaN
507,3243,E 58 St & 1 Ave,28,29,40.758924,-73.962262,In Service,1,1,E 58 St & 1 Ave,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:30:05 PM,NaN
508,3244,University Pl & E 8 St,27,31,40.731437,-73.994903,In Service,1,4,University Pl & E 8 St,NaN,NaN,NaN,NaN,NaN,False,2016-01-22 04:31:18 PM,NaN

In [19]:
df_cities = pd.read_excel('../data/stations_cities.xlsx', sheet_name='ciudades')
df_cities

     Ciudad            Pais  Poblacion
0     Paris         Francia    2161000
1     Milan          Italia    1352000
2  New York  Estados Unidos    8468000
3   Londres      Inglaterra    8982000