# Uniones Basicas en Pandas

1. Los set de datos
2. Union Interna
3. Union Izquierda
4. Union Derecha
5. Union Externa

### 1. Los set de datos

In [1]:
import pandas as pd

clientes = pd.read_csv('../data/clientes.csv')
ordenes = pd.read_csv('../data/ordenes.csv')

In [2]:
clientes

   id_cliente   nombre    pais
0           1   Alicia     USA
1           2  Roberto  Canada
2           3   Carlos  Mexico
3           4    Diana     USA

In [4]:
ordenes

   id_orden  id_cliente  monto
0       101           1    250
1       102           2    300
2       103           2    150
3       104           5    400
4       105           1    120

### 2. Union Interna

![](../img/union_interna.png)

> En una union interna (**inner join**), **se conservan unicamente las filas cuyos valores en la columna clave aparecen en ambas tablas**

> Es equivalente a hacer la **interseccion** entre dos tablas usando la columna en comun como criterio de coincidencia

![](../img/union_interna_ejemplo.png)

In [ ]:
help(pd.merge)

how : {'left', 'right', 'outer', 'inner', 'cross', 'left_anti', 'right_anti}, default 'inner'

In [ ]:
# añadir elementos del dataframe "ordenes" donde coincida con el id_cliente
union_interna = pd.merge(clientes, ordenes, on='id_cliente')
union_interna

   id_cliente   nombre    pais  id_orden  monto
0           1   Alicia     USA       101    250
1           1   Alicia     USA       105    120
2           2  Roberto  Canada       102    300
3           2  Roberto  Canada       103    150

In [7]:
# 
union_interna = pd.merge(clientes, ordenes, on='id_cliente', how='inner')
union_interna

   id_cliente   nombre    pais  id_orden  monto
0           1   Alicia     USA       101    250
1           1   Alicia     USA       105    120
2           2  Roberto  Canada       102    300
3           2  Roberto  Canada       103    150

### 3. Union Izquierda

> En una union izquierda **se conservan todas las filas de la tabla izquierda y solo las filas coincidentes de la tabla derecha** usando la columna clave como criterio. Las filas sin coincidenia en la derecha se completan con valores nulos

![](../img/union_izquierda.png)

![](../img/union_izquierda_ejemplo.png)

In [8]:
union_izquierda = pd.merge(clientes, ordenes, on='id_cliente', how='left')
union_izquierda

   id_cliente   nombre    pais  id_orden  monto
0           1   Alicia     USA     101.0  250.0
1           1   Alicia     USA     105.0  120.0
2           2  Roberto  Canada     102.0  300.0
3           2  Roberto  Canada     103.0  150.0
4           3   Carlos  Mexico       NaN    NaN
5           4    Diana     USA       NaN    NaN

### 4. Union Derecha

> En una union derecha **se conservan todas las filas de la tabla derecha y solo las filas coincidentes de la tabla izquierda**, usando la columna clave como criterio. Las filas sin coincidencia en la izquierda se completan con valores nulos.

![](../img/union_derecha.png)

![](../img/union_derecha_ejemplo.png)

In [9]:
union_derecha = pd.merge(clientes, ordenes, on='id_cliente', how='right')
union_derecha

   id_cliente   nombre    pais  id_orden  monto
0           1   Alicia     USA       101    250
1           2  Roberto  Canada       102    300
2           2  Roberto  Canada       103    150
3           5      NaN     NaN       104    400
4           1   Alicia     USA       105    120

In [10]:
union_derecha = pd.merge(ordenes, clientes, on='id_cliente', how='right')
union_derecha

   id_orden  id_cliente  monto   nombre    pais
0     101.0           1  250.0   Alicia     USA
1     105.0           1  120.0   Alicia     USA
2     102.0           2  300.0  Roberto  Canada
3     103.0           2  150.0  Roberto  Canada
4       NaN           3    NaN   Carlos  Mexico
5       NaN           4    NaN    Diana     USA

### 5. Union Externa

> En una union externa **se conservan todas las filas de ambas tablas, coincidan o no con la columna clave**. Las filas sin coincidencia se compeltan con valores nultos en las colunas de las tablas opuestas

![](../img/union_externa.png)

![](../img/union_externa_ejemplo.png)

In [11]:
union_externa = pd.merge(clientes, ordenes, on='id_cliente', how='outer')
union_externa

   id_cliente   nombre    pais  id_orden  monto
0           1   Alicia     USA     101.0  250.0
1           1   Alicia     USA     105.0  120.0
2           2  Roberto  Canada     102.0  300.0
3           2  Roberto  Canada     103.0  150.0
4           3   Carlos  Mexico       NaN    NaN
5           4    Diana     USA       NaN    NaN
6           5      NaN     NaN     104.0  400.0

# Concatenando DataFrames

### 1. Los set de datos

ventas_sucursal_1.csv

ventas_sucursal_2.csv

cantidades.csv

In [ ]:
import pandas as pd
from IPython.display import display, HTML

ventas_suc1 = pd.read_csv('../data/ventas_sucursal_1.csv')
ventas_suc2 = pd.read_csv('../data/ventas_sucursal_2.csv')
cants = pd.read_csv('../data/cantidades.csv')

def display_dfs(dfs):
    html = '<div style="display:flex">'
    for df in dfs:
        html += '<div style="margin-right: 25px">'
        html += df.to_html()
        html += '</div>'
    html += '</div>'
    display(HTML(html))

display_dfs([ventas_suc1, ventas_suc2, cants])

### 2. Problema a resolver

Objetivo: unir los 3 dataframes de manera tal que aparezcan todos los productos, con sus correspondientes montos y cantidades

### 3. Contatenacion

##### 3.1 Contatenacion Basica

In [17]:
resultado = pd.concat([ventas_suc1, ventas_suc2, cants])

display_dfs([ventas_suc1, ventas_suc2, cants, resultado])

##### 3.2 Concatenacion vertical y horizontal

In [19]:
ventas_sucs = pd.concat([ventas_suc1, ventas_suc2])
ventas_sucs

  ID_producto  Monto (USD)
0       C0125         3125
1       K1612          682
2       F2532          327
3        A003         4083
4       Z2512         5042
0       P8312          683
1       N4451         7213
2       S2215         4150

In [20]:
ventas_sucs = pd.concat([ventas_suc1, ventas_suc2], ignore_index=True)
ventas_sucs

  ID_producto  Monto (USD)
0       C0125         3125
1       K1612          682
2       F2532          327
3        A003         4083
4       Z2512         5042
5       P8312          683
6       N4451         7213
7       S2215         4150

In [21]:
resultado = pd.concat([ventas_sucs, cants], axis=1)
resultado

  ID_producto  Monto (USD) ID_producto  Cantidad
0       C0125         3125       P8312      53.0
1       K1612          682       S2215      27.0
2       F2532          327       C0125      14.0
3        A003         4083       F2532      83.0
4       Z2512         5042       K1612      62.0
5       P8312          683       Z2512      89.0
6       N4451         7213        A003     123.0
7       S2215         4150         NaN       NaN

In [ ]:
from numpy._core.numeric import  indices
# listados de los dfs originales pero con sus indices modificados
dfs = [ventas_sucs.set_index('ID_producto'), cants.set_index('ID_producto')]
# concatenacion horizontal
resultado = pd.concat(dfs, axis=1).reset_index()
resultado

  ID_producto  Monto (USD)  Cantidad
0       C0125         3125      14.0
1       K1612          682      62.0
2       F2532          327      83.0
3        A003         4083     123.0
4       Z2512         5042      89.0
5       P8312          683      53.0
6       N4451         7213       NaN
7       S2215         4150      27.0